import { Metadata } from "next";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: {
    template: "%s – Project – Deepayan",
    default: "Project – Deepayan", // a default is required when creating a template
  },
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: ReactNode }) {
  return <>{children}</>;
}
